In [0]:
import tensorflow as tf

In [2]:
from google.colab import drive
drive.mount('/content/gdrive')

Go to this URL in a browser: https://accounts.google.com/o/oauth2/auth?client_id=947318989803-6bn6qk8qdgf4n4g3pfee6491hc0brc4i.apps.googleusercontent.com&redirect_uri=urn%3Aietf%3Awg%3Aoauth%3A2.0%3Aoob&scope=email%20https%3A%2F%2Fwww.googleapis.com%2Fauth%2Fdocs.test%20https%3A%2F%2Fwww.googleapis.com%2Fauth%2Fdrive%20https%3A%2F%2Fwww.googleapis.com%2Fauth%2Fdrive.photos.readonly%20https%3A%2F%2Fwww.googleapis.com%2Fauth%2Fpeopleapi.readonly&response_type=code

Enter your authorization code:
··········
Mounted at /content/gdrive


In [0]:
import pandas as pd
data = pd.read_csv('gdrive/My Drive/Colab Notebooks/bank.csv')

In [5]:
data.head()

RowNumber  CustomerId   Surname  CreditScore Geography  Gender  Age  \
0          1    15634602  Hargrave          619    France  Female   42   
1          2    15647311      Hill          608     Spain  Female   41   
2          3    15619304      Onio          502    France  Female   42   
3          4    15701354      Boni          699    France  Female   39   
4          5    15737888  Mitchell          850     Spain  Female   43   

   Tenure    Balance  NumOfProducts  HasCrCard  IsActiveMember  \
0       2       0.00              1          1               1   
1       1   83807.86              1          0               1   
2       8  159660.80              3          1               0   
3       1       0.00              2          0               0   
4       2  125510.82              1          1               1   

   EstimatedSalary  Exited  
0        101348.88       1  
1        112542.58       0  
2        113931.57       1  
3         93826.63       0  
4         79084.10       0

In [6]:
data.columns

Index(['RowNumber', 'CustomerId', 'Surname', 'CreditScore', 'Geography',
       'Gender', 'Age', 'Tenure', 'Balance', 'NumOfProducts', 'HasCrCard',
       'IsActiveMember', 'EstimatedSalary', 'Exited'],
      dtype='object')

In [0]:
bankdf=data.drop(['RowNumber','CustomerId','Surname'],axis=1)

In [0]:
bankdf.head()

CreditScore Geography  Gender  Age  Tenure    Balance  NumOfProducts  \
0          619    France  Female   42       2       0.00              1   
1          608     Spain  Female   41       1   83807.86              1   
2          502    France  Female   42       8  159660.80              3   
3          699    France  Female   39       1       0.00              2   
4          850     Spain  Female   43       2  125510.82              1   

   HasCrCard  IsActiveMember  EstimatedSalary  Exited  
0          1               1        101348.88       1  
1          0               1        112542.58       0  
2          1               0        113931.57       1  
3          0               0         93826.63       0  
4          1               1         79084.10       0

In [8]:
bankdf.describe().T

count           mean           std     min       25%  \
CreditScore      10000.0     650.528800     96.653299  350.00    584.00   
Age              10000.0      38.921800     10.487806   18.00     32.00   
Tenure           10000.0       5.012800      2.892174    0.00      3.00   
Balance          10000.0   76485.889288  62397.405202    0.00      0.00   
NumOfProducts    10000.0       1.530200      0.581654    1.00      1.00   
HasCrCard        10000.0       0.705500      0.455840    0.00      0.00   
IsActiveMember   10000.0       0.515100      0.499797    0.00      0.00   
EstimatedSalary  10000.0  100090.239881  57510.492818   11.58  51002.11   
Exited           10000.0       0.203700      0.402769    0.00      0.00   

                        50%          75%        max  
CreditScore         652.000     718.0000     850.00  
Age                  37.000      44.0000      92.00  
Tenure                5.000       7.0000      10.00  
Balance           97198.540  127644.2400  250898.09  
NumOfProducts         1.000       2.0000       4.00  
HasCrCard             1.000       1.0000       1.00  
IsActiveMember        1.000       1.0000       1.00  
EstimatedSalary  100193.915  149388.2475  199992.48  
Exited                0.000       0.0000       1.00

**Geography and Gender attributes are catagorical. So we will use Label encoding to convert them.**

In [0]:
from sklearn import preprocessing
le = preprocessing.LabelEncoder()
bankdf['Geography'] = le.fit_transform(bankdf['Geography'])
bankdf['Gender'] = le.fit_transform(bankdf['Gender'])

In [0]:
bankdf.head()

CreditScore  Geography  Gender  Age  Tenure    Balance  NumOfProducts  \
0          619          0       0   42       2       0.00              1   
1          608          2       0   41       1   83807.86              1   
2          502          0       0   42       8  159660.80              3   
3          699          0       0   39       1       0.00              2   
4          850          2       0   43       2  125510.82              1   

   HasCrCard  IsActiveMember  EstimatedSalary  Exited  
0          1               1        101348.88       1  
1          0               1        112542.58       0  
2          1               0        113931.57       1  
3          0               0         93826.63       0  
4          1               1         79084.10       0

In [0]:
Target=pd.DataFrame(bankdf['Exited'])
Feature=bankdf.drop(['Exited'],axis=1)

In [11]:
Target.shape

(10000, 1)

In [12]:
Feature.shape

(10000, 10)

In [0]:
#Build Train / Test dataset

from sklearn.model_selection import train_test_split


X_train,X_test,y_train,y_test = train_test_split(Feature,Target,test_size=0.3)

**Model Building**

In [14]:
#Normalize Test and Train feature datasets


X_train = X_train.astype('float32')
X_test = X_test.astype('float32')

# Feature Scaling 
from sklearn.preprocessing import StandardScaler
sc = StandardScaler()
X_train = sc.fit_transform(X_train)
X_test = sc.transform(X_test)

#Normalize
from sklearn.preprocessing import Normalizer
transformer = Normalizer()
X_train = transformer.fit_transform(X_train)
X_test = transformer.transform(X_test)

/usr/local/lib/python3.6/dist-packages/sklearn/preprocessing/data.py:645: DataConversionWarning: Data with input dtype float32 were all converted to float64 by StandardScaler.
  return self.partial_fit(X, y)
/usr/local/lib/python3.6/dist-packages/sklearn/base.py:464: DataConversionWarning: Data with input dtype float32 were all converted to float64 by StandardScaler.
  return self.fit(X, **fit_params).transform(X)
/usr/local/lib/python3.6/dist-packages/ipykernel_launcher.py:10: DataConversionWarning: Data with input dtype float32 were all converted to float64 by StandardScaler.
  # Remove the CWD from sys.path while we load stuff.


In [15]:

y_train['Exited'].value_counts()

0    5571
1    1429
Name: Exited, dtype: int64

In [0]:
#Initialize Sequential model
model = tf.keras.models.Sequential()

#Add Dense layer for prediction - Keras declares weights and bias automatically
model.add(tf.keras.layers.Dense(100, input_shape=(10,),activation='relu'))

#Add 1st hidden layer
model.add(tf.keras.layers.Dense(80, kernel_initializer='normal',activation='relu'))

#Add 2nd hidden layer
model.add(tf.keras.layers.Dense(50, kernel_initializer='normal',activation='relu'))

#Add 3rd hidden layer
model.add(tf.keras.layers.Dense(30, kernel_initializer='normal',activation='relu'))
                                
#Add 4rd hidden layer
model.add(tf.keras.layers.Dense(15, kernel_initializer='normal',activation='relu'))

#Add 4rd hidden layer
model.add(tf.keras.layers.Dense(5, kernel_initializer='normal',activation='relu'))

#Add OUTPUT layer
model.add(tf.keras.layers.Dense(1, activation='sigmoid'))


In [0]:
#Create optimizer with non-default learning rate
#sgd_optimizer = tf.keras.optimizers.SGD(lr=0.03)

#Compile the model
model.compile(optimizer='adam', loss='binary_crossentropy', metrics=['accuracy'])

In [70]:
model.fit(X_train,y_train,          
          validation_data=(X_test,y_test),
          epochs=15)

Train on 7000 samples, validate on 3000 samples
Epoch 1/15
7000/7000 [==============================] - 2s 309us/sample - loss: 0.4942 - acc: 0.7950 - val_loss: 0.4216 - val_acc: 0.7973
Epoch 2/15
7000/7000 [==============================] - 2s 245us/sample - loss: 0.4260 - acc: 0.8080 - val_loss: 0.4070 - val_acc: 0.8250
Epoch 3/15
7000/7000 [==============================] - 2s 243us/sample - loss: 0.3979 - acc: 0.8363 - val_loss: 0.3728 - val_acc: 0.8483
Epoch 4/15
7000/7000 [==============================] - 2s 247us/sample - loss: 0.3675 - acc: 0.8499 - val_loss: 0.3617 - val_acc: 0.8573
Epoch 5/15
7000/7000 [==============================] - 2s 246us/sample - loss: 0.3544 - acc: 0.8569 - val_loss: 0.3579 - val_acc: 0.8530
Epoch 6/15
7000/7000 [==============================] - 2s 245us/sample - loss: 0.3450 - acc: 0.8561 - val_loss: 0.3554 - val_acc: 0.8590
Epoch 7/15
7000/7000 [==============================] - 2s 246us/sample - loss: 0.3427 - acc: 0.8600 - val_loss: 0.3537 - va

In [39]:
#Optimize model

#add batching

model.fit(X_train,y_train,          
          validation_data=(X_test,y_test),
          epochs=30,batch_size=50)


Train on 7000 samples, validate on 3000 samples
Epoch 1/30
7000/7000 [==============================] - 1s 131us/sample - loss: 0.2918 - acc: 0.8774 - val_loss: 0.3814 - val_acc: 0.8543
Epoch 2/30
7000/7000 [==============================] - 1s 135us/sample - loss: 0.2920 - acc: 0.8784 - val_loss: 0.3761 - val_acc: 0.8533
Epoch 3/30
7000/7000 [==============================] - 1s 147us/sample - loss: 0.2920 - acc: 0.8800 - val_loss: 0.3790 - val_acc: 0.8527
Epoch 4/30
7000/7000 [==============================] - 1s 146us/sample - loss: 0.2899 - acc: 0.8800 - val_loss: 0.3846 - val_acc: 0.8480
Epoch 5/30
7000/7000 [==============================] - 1s 144us/sample - loss: 0.2916 - acc: 0.8779 - val_loss: 0.3942 - val_acc: 0.8523
Epoch 6/30
7000/7000 [==============================] - 1s 142us/sample - loss: 0.2853 - acc: 0.8830 - val_loss: 0.3834 - val_acc: 0.8507
Epoch 7/30
7000/7000 [==============================] - 1s 143us/sample - loss: 0.2871 - acc: 0.8790 - val_loss: 0.3905 - va

In [72]:
y_pred=model.predict(X_test)
y_pred

array([[0.29129702],
       [0.13569033],
       [0.01420557],
       ...,
       [0.00935334],
       [0.21685287],
       [0.13947475]], dtype=float32)

In [73]:
import numpy as np

pred_y = (y_pred > 0.5).astype(np.int)
pred_y

array([[0],
       [0],
       [0],
       ...,
       [0],
       [0],
       [0]])

In [65]:
y_test

Exited
1970       0
9199       1
5077       0
5753       0
1548       0
232        0
2943       0
1595       0
8081       0
4096       0
8280       0
7364       0
4293       0
3607       0
8149       0
552        0
3556       1
3296       0
1688       0
4327       0
1622       0
1291       0
8072       1
9599       0
936        1
6356       0
7538       0
203        1
4076       1
2415       0
...      ...
3078       0
3402       0
459        0
7818       0
8002       0
2854       0
7497       0
9122       0
1857       0
6300       0
3702       0
3424       0
9267       0
512        0
5804       1
9957       0
5730       0
3986       0
8088       1
6697       0
5034       0
9308       0
2742       0
4943       0
1992       0
6173       0
7257       1
4462       1
4758       0
3345       0

[3000 rows x 1 columns]

In [74]:
from sklearn.metrics import confusion_matrix,accuracy_score
cm=confusion_matrix(y_test, pred_y)
cm

array([[2282,  110],
       [ 325,  283]])

In [75]:
accuracy_score(y_actual, pred_y)

0.855

In [0]:
def getScores(smat): 
    tp = smat[0][0] 
    fp = smat[0][1] 
    fn = smat[1][0] 
    tn = smat[1][1] 
    return tp/(tp+fp), tp/(tp+fn)

In [77]:
print("precision and recall:", getScores(cm))

precision and recall: (0.9540133779264214, 0.8753356348293058)
