

## Lab 2

Welcome to the second lab of the AIML!
In addition to implementing code, there will be questions that you must answer which relate to the lab and your implementation. Each question you will answer is preceded by a **'Question X'** header. Carefully read each question and provide you answer or code in the following textboxes with **'Answer:'** header. Your lab submission will be evaluated based on your answers to each of the questions and the implementation you provide.

# Every question is of 1 mark.

## Hypothesis Testing

The purpose of the test is to tell if there is any significant difference between two data sets.



## Overview

This module covers,

1) One sample and Two sample t-tests

2) ANOVA

3) Type I and Type II errors

4) Chi-Squared Tests

5) Linear Regression

## Question 1 

*A student is trying to decide between two GPUs. He want to use the GPU for his research to run Deep learning algorithms, so the only thing he is concerned with is speed.*

*He picks a Deep Learning algorithm and a large data set and runs it on both GPUs 15 times, timing each run in hours. Results are given in the below lists GPU1 and GPU2.*

In [1]:
import pandas as pd
GPU1 = pd.DataFrame([11,9,10,11,10,12,9,11,12,9,11,12,9,10,9])
GPU2 = pd.DataFrame([11,13,10,13,12,9,11,12,12,11,12,12,10,11,13])

#Assumption: Both the datasets (GPU1 & GPU 2) are random, independent, parametric & normally distributed

Hint: You can import ttest function from scipy to perform t tests 

Given,

Null Hypothesis : There is no significant difference between data sets

Alternate Hypothesis : There is a significant difference

*Do two-sample testing and check whether to reject Null Hypothesis or not.*

#### Answer:

In [2]:
from scipy import stats 
import numpy as np

In [3]:
stats.ttest_ind(GPU2, GPU1)

Ttest_indResult(statistic=array([2.62762951]), pvalue=array([0.01379428]))

In [4]:
#Reject Null Hypothesis

## Question 2 

He is trying a third GPU - GPU3.

In [5]:
GPU3 = pd.DataFrame([9,10,9,11,10,13,12,9,12,12,13,12,13,10,11])

#Assumption: Both the datasets (GPU1 & GPU 3) are random, independent, parametric & normally distributed

*Do two-sample testing and check whether there is significant differene between speeds of two GPUs GPU1 and GPU3.*

#### Answer:

In [6]:
stats.ttest_ind(GPU1, GPU3)

Ttest_indResult(statistic=array([-1.49889438]), pvalue=array([0.14509211]))

In [7]:
#Not rejecting Null Hypothesis

### ANOVA

## Question 3 

If you need to compare more than two data sets at a time, an ANOVA is your best bet. 

*The results from three experiments with overlapping 95% confidence intervals are given below, and we want to confirm that the results for all three experiments are not significantly different.*

#Assumption: All the 3 datasets (e1,e2 & e3) are random, independent, parametric & normally distributed
But before conducting ANOVA, test equality of variances (using Levene's test) is satisfied or not. If not, then mention that we cannot depend on the result of ANOVA

In [8]:
import pandas as pd
e1 = pd.DataFrame([1.595440,1.419730,0.000000,0.000000])
e2 = pd.DataFrame([1.433800,2.079700,0.892139,2.384740])
e3 = pd.DataFrame([0.036930,0.938018,0.995956,1.006970])

#### Answer:

In [9]:
stats.f_oneway(e1, e2, e3) 

F_onewayResult(statistic=array([2.51357623]), pvalue=array([0.13574645]))

In [10]:
#pvalue is grater, so  all three experiments are not significantly different

## Question 4 

*In one or two sentences explain about **TypeI** and **TypeII** errors.*

#### Answer:

In [11]:
# TypeI error - you reject the null hypothesis when it is actually true
# TypeII error -you accept the null hypothesis when it is actually false

## Question 5 

Explain how the higher confidence value effects TypeI and TypeII error.

#### Answer:


In [12]:
# If confidence is high ,there is less chance for Type1 error and more chance for type2

## Question 6 

*A computer expert wants to test the null hypothesis that a new GPU is no more effective than the older model.*

Lets consider that he selects the GPU which he think is more effective.

Now, find out which GPU he has selected if he made Type I error. And give reasoning about which is more effective.

**Answer:**

In [13]:
# He selected  new GPU. He made Type I error ie, the new model is actually not more effective, but he concluded that it is more efffective.

## Question 7 

From question6, if he made Type II error.

*Now, find out which GPU he has selected. And give reasoning about which is more effective.*

#### Answer:

In [14]:
# He selected  old GPU. He made Type II error ie, the new model is actually  more effective, but he concluded that it is not more efffective.

# Linear Regression


# Simple Linear Regression

## Dataset

Population of U.S. Cities

### Description
The bigcity data frame has 49 rows and 2 columns.

The measurements are the population (in 1000's) of 49 U.S. cities in 1920 and 1930. The 49 cities are a random sample taken from the 196 largest cities in 1920.

### Format
This data frame contains the following columns:

`u`
The 1920 population.

`x`
The 1930 population.

Source

The data were obtained from

Cochran, W.G. (1977) Sampling Techniques. Third edition. John Wiley

References

Davison, A.C. and Hinkley, D.V. (1997) Bootstrap Methods and Their Application. Cambridge University Press.

# Question 8 
Read the dataset given in file named 'bigcity.csv'.

In [16]:
data = pd.read_csv("bigcity.csv")

# Question 9 - Transform the dataset 
Find the number of rows in given dataset and separate the input and target variables into X and Y.
Hint: You can shape function to get the size of the dataframe

In [17]:
data.shape

(49, 3)

In [18]:
#49 rows

In [19]:
x=data[["u"]]
y=data[["x"]]

## Question 10 - Check the dataset for any missing values and also print out the correlation matrix 

You can use .isna() and .corr() functions to check NA's and correlation in the dataframe respectively

In [20]:
data.isna()

Unnamed: 0      u      x
0        False  False  False
1        False  False  False
2        False  False  False
3        False  False  False
4        False  False  False
5        False  False  False
6        False  False  False
7        False  False  False
8        False  False  False
9        False  False  False
10       False  False  False
11       False  False  False
12       False  False  False
13       False  False  False
14       False  False  False
15       False  False  False
16       False  False  False
17       False  False  False
18       False  False  False
19       False  False  False
20       False  False  False
21       False  False  False
22       False  False  False
23       False  False  False
24       False  False  False
25       False  False  False
26       False  False  False
27       False  False  False
28       False  False  False
29       False  False  False
30       False  False  False
31       False  False  False
32       False  False  False
33       False  False  False
34       False  False  False
35       False  False  False
36       False  False  False
37       False  False  False
38       False  False  False
39       False  False  False
40       False  False  False
41       False  False  False
42       False  False  False
43       False  False  False
44       False  False  False
45       False  False  False
46       False  False  False
47       False  False  False
48       False  False  False

In [21]:
data.corr()

Unnamed: 0         u         x
Unnamed: 0    1.000000 -0.024788 -0.047890
u            -0.024788  1.000000  0.981742
x            -0.047890  0.981742  1.000000

### The high correlation betwwen u and x indicates that the variable u is a good predictor of variable x

# Question 11 - Split data into train, test sets 
Divide the data into training and test sets with 80-20 split using scikit-learn. Print the shapes of training and test feature sets.*

Check: train_test_split function

In [22]:
from sklearn.model_selection import train_test_split
x_train, x_test, y_train, y_test = train_test_split(x, y, test_size=0.20, random_state=1)

In [23]:
x_train.shape

(39, 1)

In [24]:
x_test.shape

(10, 1)

In [25]:
y_train.shape

(39, 1)

In [26]:
y_test.shape

(10, 1)

# Question 12 - Find coefficients & intercept
Estimate the coefficients b0 and b1 using scikit-learn.

Check: coef_ and intercept_ functions can help you get coefficients & intercept

In [27]:
from sklearn.linear_model import LinearRegression
linreg = LinearRegression()
model1=linreg.fit(x_train, y_train)

In [28]:
model1.intercept_

array([9.71845532])

In [29]:
model1.coef_

array([[1.15945123]])

# Question 13 - Linear Relationship between feature and target 
Plot the line with b1 and b0 as slope and y-intercept.

In [77]:
import matplotlib.pyplot as plt
%matplotlib inline 


x_vals = np.array([1,2,3,4,5])
y_vals = np.array([1,2,3,4,5])
y_vals = np.array([model1.intercept_ + model1.coef_ * i for i in x_vals])

y_vals
#plt.plot(x_vals, y_vals)
    
#plt.plot(model1.coef_,model1.intercept_,'--')

array([[[10.87790656]],

       [[12.03735779]],

       [[13.19680903]],

       [[14.35626026]],

       [[15.51571149]]])

# Question 14 - Evaluation of model with scikit-learn 
Validate the model with Root Mean Squares error and R^2 score using scikit-learn. RMSE and R2 for test data and prediction

Hint: You can import mean_squared_error function & r2 (R square) from sklearn.metrics. Performing root operation over mean square error over mean square error gives you root mean square error

In [38]:
from sklearn import metrics

In [39]:
Predictions = model1.predict(x_train)

In [40]:
metrics.mean_squared_error(Predictions, y_train)

537.7499996894286

In [41]:
rmse = np.sqrt(metrics.mean_squared_error(Predictions, y_train))
rmse

23.18943724391406

In [42]:
rsquare=model1.score(x,y)
rsquare

0.9636612539991335

In [43]:
rsquare=model1.score(x_test,y_test)
rsquare

0.9181922560396981

## Question 15 - Calculate the accuracy of the model for both training and test data set 

### Hint: .score() function 

In [44]:
#Train R^2
linreg.fit(x_train,y_train)
linreg.score(x_train,y_train)

0.9682175540860046

In [45]:
#Test R^2
linreg.score(x_test,y_test)

0.9181922560396981