# Transfer Learning MNIST

* Train a simple convnet on the MNIST dataset the first 5 digits [0..4].
* Freeze convolutional layers and fine-tune dense layers for the classification of digits [5..9].

## 1. Import necessary libraries for the model

In [3]:
import numpy as np
import pandas as pd
import keras
import tensorflow as tf
import matplotlib.pyplot as plt
% matplotlib inline
import vis
from keras.datasets import mnist
from keras.models import Sequential
from keras.layers import Dense, Dropout, Flatten
from keras.layers import Conv2D, MaxPooling2D

Using TensorFlow backend.


## 2. Import MNIST data and create 2 datasets with one dataset having digits from 0 to 4 and other from 5 to 9 

In [2]:
(trainX, trainY), (testX, testY) = tf.keras.datasets.mnist.load_data()

11493376/11490434 [==============================] - 0s 0us/step


In [0]:
train_0_4 = np.isin(trainY, [0,1,2,3,4])
test_0_4 = np.isin(testY, [0,1,2,3,4])
train_5_9 = np.isin(trainY, [5,6,7,8,9])
test_5_9 = np.isin(testY, [5,6,7,8,9])

In [0]:
#Split the dataset 0-4 and 5-9

X_train04, Y_train04 = trainX[train_0_4], trainY[train_0_4]
X_test04, Y_test04 = testX[test_0_4], testY[test_0_4]

X_train59, Y_train59 = trainX[train_5_9], trainY[train_5_9]
X_test59, Y_test59 = testX[test_5_9], testY[test_5_9]

## 3. Print x_train, y_train, x_test and y_test for both the datasets

In [5]:
print(X_train04)
print(X_test04)

print(Y_train04)
print(Y_test04)

[[[0 0 0 ... 0 0 0]
  [0 0 0 ... 0 0 0]
  [0 0 0 ... 0 0 0]
  ...
  [0 0 0 ... 0 0 0]
  [0 0 0 ... 0 0 0]
  [0 0 0 ... 0 0 0]]

 [[0 0 0 ... 0 0 0]
  [0 0 0 ... 0 0 0]
  [0 0 0 ... 0 0 0]
  ...
  [0 0 0 ... 0 0 0]
  [0 0 0 ... 0 0 0]
  [0 0 0 ... 0 0 0]]

 [[0 0 0 ... 0 0 0]
  [0 0 0 ... 0 0 0]
  [0 0 0 ... 0 0 0]
  ...
  [0 0 0 ... 0 0 0]
  [0 0 0 ... 0 0 0]
  [0 0 0 ... 0 0 0]]

 ...

 [[0 0 0 ... 0 0 0]
  [0 0 0 ... 0 0 0]
  [0 0 0 ... 0 0 0]
  ...
  [0 0 0 ... 0 0 0]
  [0 0 0 ... 0 0 0]
  [0 0 0 ... 0 0 0]]

 [[0 0 0 ... 0 0 0]
  [0 0 0 ... 0 0 0]
  [0 0 0 ... 0 0 0]
  ...
  [0 0 0 ... 0 0 0]
  [0 0 0 ... 0 0 0]
  [0 0 0 ... 0 0 0]]

 [[0 0 0 ... 0 0 0]
  [0 0 0 ... 0 0 0]
  [0 0 0 ... 0 0 0]
  ...
  [0 0 0 ... 0 0 0]
  [0 0 0 ... 0 0 0]
  [0 0 0 ... 0 0 0]]]
[[[0 0 0 ... 0 0 0]
  [0 0 0 ... 0 0 0]
  [0 0 0 ... 0 0 0]
  ...
  [0 0 0 ... 0 0 0]
  [0 0 0 ... 0 0 0]
  [0 0 0 ... 0 0 0]]

 [[0 0 0 ... 0 0 0]
  [0 0 0 ... 0 0 0]
  [0 0 0 ... 0 0 0]
  ...
  [0 0 0 ... 0 0 0]
  [0 0 0 ...

In [6]:
print(X_train59)
print(X_test59)

print(Y_train59)
print(Y_test59)

[[[0 0 0 ... 0 0 0]
  [0 0 0 ... 0 0 0]
  [0 0 0 ... 0 0 0]
  ...
  [0 0 0 ... 0 0 0]
  [0 0 0 ... 0 0 0]
  [0 0 0 ... 0 0 0]]

 [[0 0 0 ... 0 0 0]
  [0 0 0 ... 0 0 0]
  [0 0 0 ... 0 0 0]
  ...
  [0 0 0 ... 0 0 0]
  [0 0 0 ... 0 0 0]
  [0 0 0 ... 0 0 0]]

 [[0 0 0 ... 0 0 0]
  [0 0 0 ... 0 0 0]
  [0 0 0 ... 0 0 0]
  ...
  [0 0 0 ... 0 0 0]
  [0 0 0 ... 0 0 0]
  [0 0 0 ... 0 0 0]]

 ...

 [[0 0 0 ... 0 0 0]
  [0 0 0 ... 0 0 0]
  [0 0 0 ... 0 0 0]
  ...
  [0 0 0 ... 0 0 0]
  [0 0 0 ... 0 0 0]
  [0 0 0 ... 0 0 0]]

 [[0 0 0 ... 0 0 0]
  [0 0 0 ... 0 0 0]
  [0 0 0 ... 0 0 0]
  ...
  [0 0 0 ... 0 0 0]
  [0 0 0 ... 0 0 0]
  [0 0 0 ... 0 0 0]]

 [[0 0 0 ... 0 0 0]
  [0 0 0 ... 0 0 0]
  [0 0 0 ... 0 0 0]
  ...
  [0 0 0 ... 0 0 0]
  [0 0 0 ... 0 0 0]
  [0 0 0 ... 0 0 0]]]
[[[0 0 0 ... 0 0 0]
  [0 0 0 ... 0 0 0]
  [0 0 0 ... 0 0 0]
  ...
  [0 0 0 ... 0 0 0]
  [0 0 0 ... 0 0 0]
  [0 0 0 ... 0 0 0]]

 [[0 0 0 ... 0 0 0]
  [0 0 0 ... 0 0 0]
  [0 0 0 ... 0 0 0]
  ...
  [0 0 0 ... 0 0 0]
  [0 0 0 ...

## ** 4. Let us take only the dataset (x_train, y_train, x_test, y_test) for Integers 0 to 4 in MNIST **
## Reshape x_train and x_test to a 4 Dimensional array (channel = 1) to pass it into a Conv2D layer

In [0]:
X_train04.shape
# Reshape data for convlution netowkr
x_train04_conv = X_train04.reshape(X_train04.shape[0], 28, 28, 1)
x_test04_conv = X_test04.reshape(X_test04.shape[0], 28, 28, 1)
input_shape = (28, 28, 1)


## 5. Normalize x_train and x_test by dividing it by 255

In [0]:

# Convert from 'uint8' to 'float32' and normalise the data to (0,1) 
x_train04_conv =  x_train04_conv.astype("float32") / 255
x_test04_conv = x_test04_conv.astype("float32") / 255


## 6. Use One-hot encoding to divide y_train and y_test into required no of output classes

In [0]:
# convert class vectors to binary class matrices
y_train_class = keras.utils.to_categorical(Y_train04, 10)
y_test_class = keras.utils.to_categorical(Y_test04, 10)

In [30]:
print(y_train_class[0])

[1. 0. 0. 0. 0. 0. 0. 0. 0. 0.]


## 7. Build a sequential model with 2 Convolutional layers with 32 kernels of size (3,3) followed by a Max pooling layer of size (2,2) followed by a drop out layer to be trained for classification of digits 0-4  

In [0]:
#Initialize the model
model = Sequential()

#Add a Convolutional Layer with 32 filters of size 3X3 and activation function as 'ReLU' 
model.add(Conv2D(32, kernel_size=(3, 3),
                 activation='relu',
                 input_shape=input_shape,name='conv_1'))

#Add a Convolutional Layer with 32 filters of size 3X3 and activation function as 'ReLU' 
model.add(Conv2D(32, (3, 3), activation='relu',name='conv_2'))

#Add a MaxPooling Layer of size 2X2 
model.add(MaxPooling2D(pool_size=(2, 2),name='max_1'))

#Apply Dropout with 0.25 probability 
model.add(Dropout(0.25,name='drop_1'))


## 8. Post that flatten the data and add 2 Dense layers with 128 neurons and neurons = output classes with activation = 'relu' and 'softmax' respectively. Add dropout layer inbetween if necessary  

In [0]:
#Flatten the layer
model.add(Flatten())

#Add Fully Connected Layer with 128 units and activation function as 'ReLU'
model.add(Dense(128, activation='relu',name='dense_1'))

#Apply Dropout with 0.5 probability 
model.add(Dropout(0.5,name='drop_2'))

#Add Fully Connected Layer with 5 units and activation function as 'softmax'
model.add(Dense(10, activation='softmax',name='dense_2'))

## 9. Print the training and test accuracy

In [33]:
from keras.optimizers import Adam
from keras.losses import categorical_crossentropy

#To use adam optimizer for learning weights with learning rate = 0.001
optimizer = Adam(lr=0.001)
#Set the loss function and optimizer for the model training
model.compile(loss=categorical_crossentropy,
              optimizer=optimizer,
              metrics=['accuracy']) 


#Training on the dataset
model.fit(x_train04_conv, y_train_class,
          batch_size=50,
          epochs=20,
          verbose=1,
          validation_data=(x_test04_conv, y_test_class))

Train on 30596 samples, validate on 5139 samples
Epoch 1/20
30596/30596 [==============================] - 7s 222us/step - loss: 0.1085 - acc: 0.9665 - val_loss: 0.0136 - val_acc: 0.9959
Epoch 2/20
30596/30596 [==============================] - 6s 209us/step - loss: 0.0324 - acc: 0.9900 - val_loss: 0.0090 - val_acc: 0.9961
Epoch 3/20
30596/30596 [==============================] - 6s 207us/step - loss: 0.0216 - acc: 0.9931 - val_loss: 0.0055 - val_acc: 0.9979
Epoch 4/20
30596/30596 [==============================] - 6s 209us/step - loss: 0.0182 - acc: 0.9941 - val_loss: 0.0059 - val_acc: 0.9981
Epoch 5/20
30596/30596 [==============================] - 6s 208us/step - loss: 0.0151 - acc: 0.9949 - val_loss: 0.0035 - val_acc: 0.9990
Epoch 6/20
30596/30596 [==============================] - 6s 209us/step - loss: 0.0131 - acc: 0.9955 - val_loss: 0.0057 - val_acc: 0.9981
Epoch 7/20
30596/30596 [==============================] - 6s 209us/step - loss: 0.0103 - acc: 0.9964 - val_loss: 0.0060 - v

In [34]:
#Testing the model on test set
score = model.evaluate(x_test04_conv, y_test_class)
print('Test loss:', score[0])
print('Test accuracy:', score[1])

5139/5139 [==============================] - 0s 92us/step
Test loss: 0.004541439346094206
Test accuracy: 0.9986378672893559


## 10. Make only the dense layers to be trainable and convolutional layers to be non-trainable

In [35]:
#Freezing layers in the model which don't have 'dense' in their name
for layer in model.layers:
  if('dense' not in layer.name): #prefix detection to freeze layers which does not have dense
    #Freezing a layer
    layer.trainable = False

#Module to print colourful statements
from termcolor import colored

#Check which layers have been frozen 
for layer in model.layers:
  print (colored(layer.name, 'blue'))
  print (colored(layer.trainable, 'red'))

conv_1
False
conv_2
False
max_1
False
drop_1
False
flatten_2
False
dense_1
True
drop_2
False
dense_2
True


In [36]:
np.unique(Y_train59)

array([5, 6, 7, 8, 9], dtype=uint8)

## 11. Use the model trained on 0 to 4 digit classification and train it on the dataset which has digits 5 to 9  (Using Transfer learning keeping only the dense layers to be trainable)

In [0]:
X_train59.shape
# Reshape data for convlution netowkr
x_train59_conv = X_train59.reshape(X_train59.shape[0], 28, 28, 1)
x_test59_conv = X_test59.reshape(X_test59.shape[0], 28, 28, 1)
input_shape = (28, 28, 1)

# Convert from 'uint8' to 'float32' and normalise the data to (0,1) 
x_train59_conv =  x_train59_conv.astype("float32") / 255
x_test59_conv = x_test59_conv.astype("float32") / 255

# convert class vectors to binary class matrices
y_train_class59 = keras.utils.to_categorical(Y_train59, num_classes=10)
y_test_class59 = keras.utils.to_categorical(Y_test59, num_classes=10)

In [38]:
#Training on the dataset
model.fit(x_train59_conv, y_train_class59,
          batch_size=50,
          epochs=20,
          verbose=1,
          validation_data=(x_test59_conv,y_test_class59))

Train on 29404 samples, validate on 4861 samples
Epoch 1/20
  800/29404 [..............................] - ETA: 6s - loss: 6.2113 - acc: 0.0500

/usr/local/lib/python3.6/dist-packages/keras/engine/training.py:490: UserWarning: Discrepancy between trainable weights and collected trainable weights, did you set `model.trainable` without calling `model.compile` after ?
  'Discrepancy between trainable weights and collected trainable'


29404/29404 [==============================] - 6s 209us/step - loss: 0.7925 - acc: 0.7203 - val_loss: 0.1222 - val_acc: 0.9615
Epoch 2/20
29404/29404 [==============================] - 6s 204us/step - loss: 0.3012 - acc: 0.8922 - val_loss: 0.0782 - val_acc: 0.9768
Epoch 3/20
29404/29404 [==============================] - 6s 206us/step - loss: 0.2153 - acc: 0.9270 - val_loss: 0.0686 - val_acc: 0.9788
Epoch 4/20
29404/29404 [==============================] - 6s 204us/step - loss: 0.1751 - acc: 0.9418 - val_loss: 0.0573 - val_acc: 0.9823
Epoch 5/20
29404/29404 [==============================] - 6s 204us/step - loss: 0.1501 - acc: 0.9511 - val_loss: 0.0500 - val_acc: 0.9866
Epoch 6/20
29404/29404 [==============================] - 6s 203us/step - loss: 0.1328 - acc: 0.9570 - val_loss: 0.0462 - val_acc: 0.9866
Epoch 7/20
29404/29404 [==============================] - 6s 204us/step - loss: 0.1193 - acc: 0.9626 - val_loss: 0.0468 - val_acc: 0.9866
Epoch 8/20
29404/29404 [=====================

## 12. Print the accuracy for classification of digits 5 to 9

In [40]:
score = model.evaluate(x_test59_conv, y_test_class59)
print('Test loss:', score[0])
print('Test accuracy:', score[1])

4861/4861 [==============================] - 0s 95us/step
Test loss: 0.024319507127918954
Test accuracy: 0.9934169923883974


## Sentiment analysis <br> 

The objective of the second problem is to perform Sentiment analysis from the tweets data collected from the users targeted at various mobile devices.
Based on the tweet posted by a user (text), we will classify if the sentiment of the user targeted at a particular mobile device is positive or not.

### 13. Read the dataset (tweets.csv) and drop the NA's while reading the dataset

In [1]:
from google.colab import drive
drive.mount('/content/gdrive')

Go to this URL in a browser: https://accounts.google.com/o/oauth2/auth?client_id=947318989803-6bn6qk8qdgf4n4g3pfee6491hc0brc4i.apps.googleusercontent.com&redirect_uri=urn%3Aietf%3Awg%3Aoauth%3A2.0%3Aoob&scope=email%20https%3A%2F%2Fwww.googleapis.com%2Fauth%2Fdocs.test%20https%3A%2F%2Fwww.googleapis.com%2Fauth%2Fdrive%20https%3A%2F%2Fwww.googleapis.com%2Fauth%2Fdrive.photos.readonly%20https%3A%2F%2Fwww.googleapis.com%2Fauth%2Fpeopleapi.readonly&response_type=code

Enter your authorization code:
··········
Mounted at /content/gdrive


In [32]:
tweetsDf = pd.read_csv('/content/gdrive/My Drive/Colab Notebooks/tweets.csv',encoding = 'ISO-8859-1',keep_default_na=False)
tweetsDf.head()

tweet_text  ... is_there_an_emotion_directed_at_a_brand_or_product
0  .@wesley83 I have a 3G iPhone. After 3 hrs twe...  ...                                   Negative emotion
1  @jessedee Know about @fludapp ? Awesome iPad/i...  ...                                   Positive emotion
2  @swonderlin Can not wait for #iPad 2 also. The...  ...                                   Positive emotion
3  @sxsw I hope this year's festival isn't as cra...  ...                                   Negative emotion
4  @sxtxstate great stuff on Fri #SXSW: Marissa M...  ...                                   Positive emotion

[5 rows x 3 columns]

In [18]:
tweetsDf.count()

tweet_text                                            9093
emotion_in_tweet_is_directed_at                       9093
is_there_an_emotion_directed_at_a_brand_or_product    9093
dtype: int64

In [19]:
tweetsDf.isnull().sum()

tweet_text                                            0
emotion_in_tweet_is_directed_at                       0
is_there_an_emotion_directed_at_a_brand_or_product    0
dtype: int64

### 14. Preprocess the text and add the preprocessed text in a column with name `text` in the dataframe.

In [0]:
def preprocess(text):
    try:
        return text.encode().decode('ascii')
    except Exception as e:
        return e

In [0]:
tweetsDf['text'] = [preprocess(text) for text in tweetsDf.tweet_text]

In [46]:
tweetsDf.head()

tweet_text  ...                                               text
0  .@wesley83 I have a 3G iPhone. After 3 hrs twe...  ...  .@wesley83 I have a 3G iPhone. After 3 hrs twe...
1  @jessedee Know about @fludapp ? Awesome iPad/i...  ...  @jessedee Know about @fludapp ? Awesome iPad/i...
2  @swonderlin Can not wait for #iPad 2 also. The...  ...  @swonderlin Can not wait for #iPad 2 also. The...
3  @sxsw I hope this year's festival isn't as cra...  ...  @sxsw I hope this year's festival isn't as cra...
4  @sxtxstate great stuff on Fri #SXSW: Marissa M...  ...  @sxtxstate great stuff on Fri #SXSW: Marissa M...

[5 rows x 4 columns]

### 15. Consider only rows having Positive emotion and Negative emotion and remove other rows from the dataframe.

In [0]:
tweetEmoDf = tweetsDf[(tweetsDf['is_there_an_emotion_directed_at_a_brand_or_product'] == 'Positive emotion') | (tweetsDf['is_there_an_emotion_directed_at_a_brand_or_product'] == 'Negative emotion')]

In [48]:
tweetEmoDf.head()

tweet_text  ...                                               text
0  .@wesley83 I have a 3G iPhone. After 3 hrs twe...  ...  .@wesley83 I have a 3G iPhone. After 3 hrs twe...
1  @jessedee Know about @fludapp ? Awesome iPad/i...  ...  @jessedee Know about @fludapp ? Awesome iPad/i...
2  @swonderlin Can not wait for #iPad 2 also. The...  ...  @swonderlin Can not wait for #iPad 2 also. The...
3  @sxsw I hope this year's festival isn't as cra...  ...  @sxsw I hope this year's festival isn't as cra...
4  @sxtxstate great stuff on Fri #SXSW: Marissa M...  ...  @sxtxstate great stuff on Fri #SXSW: Marissa M...

[5 rows x 4 columns]

### 16. Represent text as numerical data using `CountVectorizer` and get the document term frequency matrix

#### Use `vect` as the variable name for initialising CountVectorizer.

In [0]:
from sklearn.feature_extraction.text import CountVectorizer

# Initialize the "CountVectorizer" object, which is scikit-learn's
# bag of words tool.  
vect = CountVectorizer(analyzer = "word",   \
                             tokenizer = None,    \
                             preprocessor = None, \
                             stop_words = None,   \
                             max_features = 7500) 

In [0]:
tweetEmoCVDf = vect.fit_transform(tweetEmoDf['tweet_text']).toarray()

In [59]:
tweetEmoCVDf.shape

(3548, 6022)

In [60]:
print(tweetEmoCVDf)

[[0 0 0 ... 0 0 0]
 [0 0 0 ... 0 0 0]
 [0 0 0 ... 0 0 0]
 ...
 [0 0 0 ... 0 0 0]
 [0 0 0 ... 0 0 0]
 [0 0 0 ... 0 0 0]]


### 17. Find number of different words in vocabulary

In [62]:
vocab = vect.get_feature_names()
print(len(vocab))

6022


#### Tip: To see all available functions for an Object use dir

### 18. Find out how many Positive and Negative emotions are there.

Hint: Use value_counts on that column

In [64]:
tweetEmoDf['is_there_an_emotion_directed_at_a_brand_or_product'].value_counts()

Positive emotion    2978
Negative emotion     570
Name: is_there_an_emotion_directed_at_a_brand_or_product, dtype: int64

### 19. Change the labels for Positive and Negative emotions as 1 and 0 respectively and store in a different column in the same dataframe named 'Label'

Hint: use map on that column and give labels

In [66]:
emotions = {'Positive emotion' : 1,
                'Negative emotion' : 0 }

tweetEmoDf['Label'] = tweetEmoDf['is_there_an_emotion_directed_at_a_brand_or_product'].map(emotions)

tweetEmoDf.head()

/usr/local/lib/python3.6/dist-packages/ipykernel_launcher.py:4: SettingWithCopyWarning: 
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: http://pandas.pydata.org/pandas-docs/stable/indexing.html#indexing-view-versus-copy
  after removing the cwd from sys.path.


tweet_text  ... Label
0  .@wesley83 I have a 3G iPhone. After 3 hrs twe...  ...     0
1  @jessedee Know about @fludapp ? Awesome iPad/i...  ...     1
2  @swonderlin Can not wait for #iPad 2 also. The...  ...     1
3  @sxsw I hope this year's festival isn't as cra...  ...     0
4  @sxtxstate great stuff on Fri #SXSW: Marissa M...  ...     1

[5 rows x 5 columns]

### 20. Define the feature set (independent variable or X) to be `text` column and `labels` as target (or dependent variable)  and divide into train and test datasets

In [0]:
X = tweetEmoCVDf
y = tweetEmoDf['Label']

In [0]:
from sklearn.model_selection import train_test_split
X_train, X_test, y_train, y_test = train_test_split(X, y, test_size=0.2)

## 21. **Predicting the sentiment:**


### Use Naive Bayes and Logistic Regression and their accuracy scores for predicting the sentiment of the given text

In [0]:
from sklearn.naive_bayes import GaussianNB
from sklearn.linear_model import LogisticRegression

In [0]:
model_NB = GaussianNB().fit(X_train, y_train)

In [0]:
model_LR = LogisticRegression(random_state=0, solver='lbfgs',multi_class='multinomial').fit(X_train, y_train)

In [72]:
model_NB.score(X_test, y_test)

0.7718309859154929

In [73]:
model_LR.score(X_test, y_test)

0.8873239436619719

## 22. Create a function called `tokenize_predict` which can take count vectorizer object as input and prints the accuracy for x (text) and y (labels)

In [0]:
from sklearn.naive_bayes import MultinomialNB
from sklearn import metrics

Xf = tweetEmoDf['tweet_text']
yf = tweetEmoDf['Label']

Xf_train, Xf_test, yf_train, yf_test = train_test_split(Xf, yf, test_size=0.2)

In [0]:
def tokenize_predict(vect):
    X_train_dtm = vect.fit_transform(Xf_train)
    print('Features: ', X_train_dtm.shape[1])
    X_test_dtm = vect.transform(Xf_test)
    nb = MultinomialNB()
    nb.fit(X_train_dtm, yf_train)
    y_pred_class = nb.predict(X_test_dtm)
    print('Accuracy: ', metrics.accuracy_score(yf_test, y_pred_class))

### Create a count vectorizer function which includes n_grams = 1,2  and pass it to tokenize_predict function to print the accuracy score

In [82]:
vect1 = CountVectorizer(analyzer = "word",   \
                             tokenizer = None,    \
                             preprocessor = None, \
                             stop_words = None,   \
                             ngram_range = (1,2), \
                             max_features = 7500) 

tokenize_predict(vect1)


Features:  7500
Accuracy:  0.8619718309859155


### Create a count vectorizer function with stopwords = 'english'  and pass it to tokenize_predict function to print the accuracy score

In [83]:
vect2 = CountVectorizer(analyzer = "word",   \
                             tokenizer = None,    \
                             preprocessor = None, \
                             stop_words = 'english',   \
                             ngram_range = (1,2), \
                             max_features = 7500) 

tokenize_predict(vect2)

Features:  7500
Accuracy:  0.8718309859154929


### Create a count vectorizer function with stopwords = 'english' and max_features =300  and pass it to tokenize_predict function to print the accuracy score

In [84]:
vect3 = CountVectorizer(analyzer = "word",   \
                             tokenizer = None,    \
                             preprocessor = None, \
                             stop_words = 'english',   \
                             ngram_range = (1,2), \
                             max_features = 300) 
tokenize_predict(vect3)

Features:  300
Accuracy:  0.7830985915492957


### Create a count vectorizer function with n_grams = 1,2  and max_features = 15000  and pass it to tokenize_predict function to print the accuracy score

In [85]:
vect4 = CountVectorizer(analyzer = "word",   \
                             tokenizer = None,    \
                             preprocessor = None, \
                             stop_words = 'english',   \
                             ngram_range = (1,2), \
                             max_features = 15000) 
tokenize_predict(vect4)

Features:  15000
Accuracy:  0.8704225352112676


### Create a count vectorizer function with n_grams = 1,2  and include terms that appear at least 2 times (min_df = 2)  and pass it to tokenize_predict function to print the accuracy score

In [0]:
vect5 = CountVectorizer(analyzer = "word",   \
                             tokenizer = None,    \
                             preprocessor = None, \
                             stop_words = 'english',   \
                             ngram_range = (1,2), \
                             min_df = 2, \
                             max_features = 15000) 

In [87]:
tokenize_predict(vect5)

Features:  6491
Accuracy:  0.8704225352112676
