# Sentiment Classification


### Generate Word Embeddings and retrieve outputs of each layer with Keras based on Classification task

Word embeddings are a type of word representation that allows words with similar meaning to have a similar representation.

It is a distributed representation for text that is perhaps one of the key breakthroughs for the impressive performance of deep learning methods on challenging natural language processing problems.

We willl use the imdb dataset to learn word embeddings as we train our dataset. This dataset contains 25,000 movie reviews from IMDB, labeled with sentiment (positive or negative). 



### Dataset

`from keras.datasets import imdb`

Dataset of 25,000 movies reviews from IMDB, labeled by sentiment (positive/negative). Reviews have been preprocessed, and each review is encoded as a sequence of word indexes (integers). For convenience, the words are indexed by their frequency in the dataset, meaning the for that has index 1 is the most frequent word. Use the first 20 words from each review to speed up training, using a max vocab size of 10,000.

As a convention, "0" does not stand for a specific word, but instead is used to encode any unknown word.


### Aim

1. Import test and train data  
2. Import the labels ( train and test) 
3. Get the word index and then Create key value pair for word and word_id. (12.5 points)
4. Build a Sequential Model using Keras for Sentiment Classification task. (10 points)
5. Report the Accuracy of the model. (5 points)  
6. Retrive the output of each layer in keras for a given single test sample from the trained model you built. (2.5 points)


In [0]:
import numpy as np

#### Usage:

In [3]:
from keras.datasets import imdb

# save np.load
np_load_old = np.load

# modify the default parameters of np.load
np.load = lambda *a,**k: np_load_old(*a, allow_pickle=True, **k)

vocab_size = 10000 #vocab size

(x_train, y_train), (x_test, y_test) = imdb.load_data(num_words=vocab_size) # vocab_size is no.of words to consider from the dataset, ordering based on frequency.


# restore np.load for future normal usage
np.load = np_load_old


x_train

17473536/17464789 [==============================] - 0s 0us/step


array([list([1, 14, 22, 16, 43, 530, 973, 1622, 1385, 65, 458, 4468, 66, 3941, 4, 173, 36, 256, 5, 25, 100, 43, 838, 112, 50, 670, 2, 9, 35, 480, 284, 5, 150, 4, 172, 112, 167, 2, 336, 385, 39, 4, 172, 4536, 1111, 17, 546, 38, 13, 447, 4, 192, 50, 16, 6, 147, 2025, 19, 14, 22, 4, 1920, 4613, 469, 4, 22, 71, 87, 12, 16, 43, 530, 38, 76, 15, 13, 1247, 4, 22, 17, 515, 17, 12, 16, 626, 18, 2, 5, 62, 386, 12, 8, 316, 8, 106, 5, 4, 2223, 5244, 16, 480, 66, 3785, 33, 4, 130, 12, 16, 38, 619, 5, 25, 124, 51, 36, 135, 48, 25, 1415, 33, 6, 22, 12, 215, 28, 77, 52, 5, 14, 407, 16, 82, 2, 8, 4, 107, 117, 5952, 15, 256, 4, 2, 7, 3766, 5, 723, 36, 71, 43, 530, 476, 26, 400, 317, 46, 7, 4, 2, 1029, 13, 104, 88, 4, 381, 15, 297, 98, 32, 2071, 56, 26, 141, 6, 194, 7486, 18, 4, 226, 22, 21, 134, 476, 26, 480, 5, 144, 30, 5535, 18, 51, 36, 28, 224, 92, 25, 104, 4, 226, 65, 16, 38, 1334, 88, 12, 16, 283, 5, 16, 4472, 113, 103, 32, 15, 16, 5345, 19, 178, 32]),
       list([1, 194, 1153, 194, 8255, 78, 228,

In [0]:
from keras.preprocessing.sequence import pad_sequences
vocab_size = 10000 #vocab size
maxlen = 20  #number of word used from each review

In [0]:
#make all sequences of the same length
x_train = pad_sequences(x_train, maxlen=maxlen)
x_test =  pad_sequences(x_test, maxlen=maxlen)

In [35]:
x_train

array([[  65,   16,   38, ...,   19,  178,   32],
       [  23,    4, 1690, ...,   16,  145,   95],
       [1352,   13,  191, ...,    7,  129,  113],
       ...,
       [  11, 1818, 7561, ...,    4, 3586,    2],
       [  92,  401,  728, ...,   12,    9,   23],
       [ 764,   40,    4, ...,  204,  131,    9]], dtype=int32)

In [7]:
y_train

array([1, 0, 0, ..., 0, 1, 0])

## Build Keras Embedding Layer Model
We can think of the Embedding layer as a dicionary that maps a index assigned to a word to a word vector. This layer is very flexible and can be used in a few ways:

* The embedding layer can be used at the start of a larger deep learning model. 
* Also we could load pre-train word embeddings into the embedding layer when we create our model.
* Use the embedding layer to train our own word2vec models.

The keras embedding layer doesn't require us to onehot encode our words, instead we have to give each word a unqiue intger number as an id. For the imdb dataset we've loaded this has already been done, but if this wasn't the case we could use sklearn [LabelEncoder](http://scikit-learn.org/stable/modules/generated/sklearn.preprocessing.LabelEncoder.html).

In [10]:
from keras.models import Sequential
from keras.layers import LSTM, SimpleRNN, Dense
from keras.layers import Flatten
from keras.layers.embeddings import Embedding

# define the model
model = Sequential()
model.add(Embedding(vocab_size, 8, input_length=maxlen))
model.add(
    SimpleRNN(
        1, return_sequences=False, dropout=0.1))
model.add(Dense(1, activation='sigmoid'))

W0630 08:23:20.524909 140370308241280 deprecation_wrapper.py:119] From /usr/local/lib/python2.7/dist-packages/keras/backend/tensorflow_backend.py:517: The name tf.placeholder is deprecated. Please use tf.compat.v1.placeholder instead.

W0630 08:23:20.538605 140370308241280 deprecation_wrapper.py:119] From /usr/local/lib/python2.7/dist-packages/keras/backend/tensorflow_backend.py:4138: The name tf.random_uniform is deprecated. Please use tf.random.uniform instead.

W0630 08:23:20.607131 140370308241280 deprecation_wrapper.py:119] From /usr/local/lib/python2.7/dist-packages/keras/backend/tensorflow_backend.py:133: The name tf.placeholder_with_default is deprecated. Please use tf.compat.v1.placeholder_with_default instead.

W0630 08:23:20.617249 140370308241280 deprecation.py:506] From /usr/local/lib/python2.7/dist-packages/keras/backend/tensorflow_backend.py:3445: calling dropout (from tensorflow.python.ops.nn_ops) with keep_prob is deprecated and will be removed in a future version.
Ins

In [18]:
# compile the model
model.compile(optimizer='adam', loss='binary_crossentropy', metrics=['acc'])
# summarize the model
print(model.summary())

_________________________________________________________________
Layer (type)                 Output Shape              Param #   
embedding_1 (Embedding)      (None, 20, 8)             80000     
_________________________________________________________________
simple_rnn_1 (SimpleRNN)     (None, 1)                 10        
_________________________________________________________________
dense_1 (Dense)              (None, 1)                 2         
Total params: 80,012
Trainable params: 80,012
Non-trainable params: 0
_________________________________________________________________
None


In [46]:
# fit the model
model.fit(x_train, y_train,batch_size=20, epochs=20, verbose=1)
# evaluate the model
loss, accuracy = model.evaluate(x_test, y_test, verbose=1)
print('Accuracy: %f' % (accuracy*100))


Epoch 1/20
25000/25000 [==============================] - 16s 621us/step - loss: 0.2157 - acc: 0.9305
Epoch 2/20
25000/25000 [==============================] - 16s 627us/step - loss: 0.2146 - acc: 0.9314
Epoch 3/20
25000/25000 [==============================] - 16s 626us/step - loss: 0.2135 - acc: 0.9322
Epoch 4/20
25000/25000 [==============================] - 16s 620us/step - loss: 0.2133 - acc: 0.9308
Epoch 5/20
25000/25000 [==============================] - 15s 619us/step - loss: 0.2129 - acc: 0.9317
Epoch 6/20
25000/25000 [==============================] - 15s 617us/step - loss: 0.2122 - acc: 0.9337
Epoch 7/20
25000/25000 [==============================] - 15s 615us/step - loss: 0.2135 - acc: 0.9304
Epoch 8/20
25000/25000 [==============================] - 16s 622us/step - loss: 0.2131 - acc: 0.9320
Epoch 9/20
25000/25000 [==============================] - 15s 616us/step - loss: 0.2139 - acc: 0.9323
Epoch 10/20
25000/25000 [==============================] - 15s 616us/step - loss: 

## Retrive the output of each layer in keras for a given single test sample from the trained model you built

In [0]:
#Created a function to get output for each layer using Keras Function

from keras import backend as K

inp = model.input                                           # input placeholder
outputs = [layer.output for layer in model.layers]          # all layer outputs
functors = [K.function([inp, K.learning_phase()], [out]) for out in outputs]    # evaluation functions


In [49]:
x_train[1].reshape(1,20)

array([[  23,    4, 1690,   15,   16,    4, 1355,    5,   28,    6,   52,
         154,  462,   33,   89,   78,  285,   16,  145,   95]],
      dtype=int32)

In [53]:
# Passed x_train single row to function and output is recieved.

layer_outs = [func([x_train[2].reshape(1,20), 1.]) for func in functors]
print layer_outs

[[array([[[ 2.19319269e-01, -9.21702571e-03,  1.34506822e-01,
          9.76549760e-02, -1.87273845e-01, -1.05265282e-01,
          6.50103018e-02, -5.37668765e-02],
        [-3.49600874e-02, -6.79610968e-02, -8.13248567e-03,
         -1.47515619e-02,  4.20538709e-02,  1.92904007e-02,
          5.64743823e-04,  1.68797709e-02],
        [ 1.14885401e-02,  5.81286773e-02,  1.62117518e-02,
         -6.45283163e-02,  4.89249779e-03,  3.31173725e-02,
          4.35640141e-02,  3.54136666e-03],
        [-3.74605432e-02, -2.98223998e-02,  1.71214323e-02,
          5.75009994e-02,  2.84163840e-02,  6.42462587e-03,
          4.02870635e-03,  2.69408803e-02],
        [-2.51379469e-03,  6.22642180e-03,  9.23890546e-02,
         -7.36247227e-02, -4.63870876e-02,  1.17304862e-01,
         -6.10554740e-02, -1.11838141e-02],
        [ 1.83566958e-02, -1.06423654e-01, -3.34315300e-02,
         -6.03454970e-02,  6.19241521e-02,  5.04820049e-02,
         -7.26725832e-02,  4.16062362e-02],
        [-3.77